include:
  - project: "dakual/gitlab-ci-terraform-ecs"
    ref: main
    file: "ci-templates/terraform.yml"

"Application Deployment":
  stage: deploy
  when: manual
  trigger:
    strategy: depend
    include:
      - project: "dakual/gitlab-ci-terraform-ecs"
        ref: main
        file: "ci-templates/application.yml"