---
stages:
  - build
  - apply

variables:
  RUNNER_TAGS: dev
  REPOSITORY: 632296647497.dkr.ecr.eu-central-1.amazonaws.com/gitlab-ci-ecs

build-push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY
  script:
    - cd app
    - docker build --tag $REPOSITORY:$CI_COMMIT_SHORT_SHA --tag $REPOSITORY:latest .
    - docker push $REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY:latest
  tags:
    - ${RUNNER_TAGS}