---
stages:
  - build
  - apply

variables:
  RUNNER_TAGS: dev
  REPOSITORY: 632296647497.dkr.ecr.eu-central-1.amazonaws.com/gitlab-ci-ecs

build-push:
  stage: build
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - cd app
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY
    - docker build --tag $REPOSITORY:$CI_COMMIT_SHORT_SHA --tag $REPOSITORY:latest .
    - docker push $REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY:latest
  tags:
    - ${RUNNER_TAGS}

build-push2:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY
    - docker build --tag $REPOSITORY:$CI_COMMIT_SHORT_SHA --tag $REPOSITORY:latest .
    - docker push $REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY:latest