---
stages:
  - development
  - staging
  - production

variables:
  RUNNER_TAGS: dev
  TF_VERSION: "1.3.6"
  TF_CLOUD_CREDENTIALS: |
    credentials "app.terraform.io" {
      token = "${TF_CLOUD_TEAM_TOKEN}"
    }

terraform-dev:
  stage: development
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-dev
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}
    AWS_REGION: "eu-central-1"
  trigger:
    include:
      - project: 'dakual/gitlab-ci-terraform-ecs'
        ref: main
        file:
          - 'ci-templates/infa-gitlab-ci.yml'
          - 'ci-templates/workflows/gitlab-ci-ecs-dev.yml'
    strategy: depend


terraform-stg:
  stage: staging
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-stg
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}
    AWS_REGION: "eu-central-1"
  trigger:
    include:
      - project: 'dakual/gitlab-ci-terraform-ecs'
        ref: main
        file:
          - 'ci-templates/infa-gitlab-ci.yml'
          - 'ci-templates/workflows/gitlab-ci-ecs-stg.yml'
    strategy: depend
  needs:
    - job: "terraform-dev"


terraform-prd:
  stage: production
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-prd
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}
    AWS_REGION: "eu-central-1"
  trigger:
    include:
      - project: 'dakual/gitlab-ci-terraform-ecs'
        ref: main
        file:
          - 'ci-templates/infa-gitlab-ci.yml'
          - 'ci-templates/workflows/gitlab-ci-ecs-prd.yml'
    strategy: depend
  needs:
    - job: "terraform-stg"