.prd:
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-prd

.prd:rw:
  extends: .prd
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}

.prd:ro:
  extends: .prd
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_RO_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_RO_AWS_ACCESS_KEY_SECRET}
  
prd:infra:validate:
  extends: 
    - .prd:ro
    - .terraform:validate

prd:infra:plan:
  extends: 
    - .prd:ro
    - .terraform:plan
  needs:
    - prd:infra:validate

prd:infra:apply:
  extends: 
    - .prd:rw
    - .terraform:apply
  needs:
    - prd:infra:plan
  when: manual

prd:infra:destroy-plan:
  extends: 
    - .prd:ro
    - .terraform:destroy-plan
  needs:
    - dev:infra:validate
  when: manual

prd:infra:destroy-apply:
  extends:
    - .prd:rw
    - .terraform:destroy-apply
  needs:
    - prd:infra:destroy-plan
  when: manual
  
