.prd:
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-prd

.prd:rw:
  extends: .prd
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}

.prd:ro:
  extends: .prd
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_RO_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_RO_AWS_ACCESS_KEY_SECRET}