.dev:
  variables:
    TF_WORKSPACE: gitlab-ci-ecs-dev

.dev:rw:
  extends: .dev
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}

.dev:ro:
  extends: .dev
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_RO_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_RO_AWS_ACCESS_KEY_SECRET}
  
dev:infra:validate:
  extends: 
    - .dev:ro
    - .terraform:validate

dev:infra:plan:
  extends: 
    - .dev:ro
    - .terraform:plan
  needs:
    - dev:infra:validate

dev:infra:apply:
  extends: 
    - .dev:rw
    - .terraform:apply
  needs:
    - dev:infra:plan
  when: manual

dev:infra:destroy-plan:
  extends: 
    - .dev:ro
    - .terraform:destroy-plan
  needs:
    - dev:infra:validate
  when: manual

dev:infra:destroy-apply:
  extends:
    - .dev:rw
    - .terraform:destroy-apply
  needs:
    - dev:infra:destroy-plan
  when: manual
  
