prd:infra:validate:
  extends: 
    - .terraform:validate

prd:infra:plan:
  extends: 
    - .terraform:plan
  needs:
    - prd:infra:validate

prd:infra:apply:
  extends: 
    - .terraform:apply
  needs:
    - prd:infra:plan
  when: manual

prd:infra:destroy-plan:
  extends: 
    - .terraform:destroy-plan
  needs:
    - prd:infra:validate
  when: manual

prd:infra:destroy-apply:
  extends:
    - .terraform:destroy-apply
  needs:
    - prd:infra:destroy-plan
  when: manual
  
