environment: dev
region: eu-central-1
cidr: 10.0.0.0/16
availability_zones:
  - eu-central-1a
  - eu-central-1b
private_subnets:
  - 10.0.0.0/20
  - 10.0.32.0/20
public_subnets:
  - 10.0.16.0/20
  - 10.0.48.0/20
rds:
  db_name: demo
  db_username: admin
